### ISSUE TITLE
`div`

### ISSUE THREAD

**Issue by ghost** [SmeetaPatel/prj-rev-bwfs-dasmoto#2]
https://github.com/SmeetaPatel/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L9-L17

Nice job using `div` tags to divide your page into logical sections, like the three equivalent product sections and the header section. 👍 

Consider using the same class name for each `div` tag, like `product` or `item`, since each product section is mostly styled the same way and can be styled as a group, and using a different ID for each `h2` tag, since each heading needs to be selected and styled individually.

**Comment by SmeetaPatel** [comment]
<div class="product">
  <h2 id="brush">Brushes</h2>
  <img src="./resources/images/hacksaw.jpeg" alt="Hacksaw" />
  <h3>Hacksaw Brushes</h3>
  <p>Made of the highest quality oak. Hacksaw brushes are known for their weight
  and ability to hold paint in large amounts. Available in different sizes.</p>
  <span class="price">Starting at $3.00/brush</span>
 </div>
 <div class="product">
   <h2 id="frame">Frames</h2>
   <img src="./resources/images/frames.jpeg" alt="Frames" />
   <h3>Art Frames (Assorted)</h3>
   <p>Assorted frames made from different material, including MDF, birchwood,
   and PDE. Select frames can be sanded and painted according to your needs. </p>
   <span class="price">Starting at $2.00/frame</span>
  </div>
