### ISSUE TITLE
Include assets

### ISSUE THREAD

**Issue by ghost** [SmeetaPatel/prj-rev-bwfs-dasmoto#3]
https://github.com/SmeetaPatel/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L11

Include your website's assets (in this case images) in your project and provide a relative file path to them in your `img` tags. 

It's always better to provide static assets up front instead of depending on external URLs that could fail or otherwise become unavailable.

**Comment by SmeetaPatel** [comment]
<img src="./resources/images/hacksaw.jpeg" alt="Hacksaw" />
