### ISSUE TITLE
`img alt`

### ISSUE THREAD

**Issue by ghost** [SmeetaPatel/prj-rev-bwfs-dasmoto#4]
https://github.com/SmeetaPatel/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L11

Give your `img` tags an `alt` attribute with a value that adequately describes the image, just in case your website is not able to load it. 

Doing so will help improve the accessibility of your website, which might be accessed by visually impaired users on e-readers or other devices that might deliberately neglect images-- as well as any other time that your website is just unable to render images.

**Comment by SmeetaPatel** [comment]
h1{
  font-size: 100px;
  color: khaki;
  font-weight: bold;
  text-align: center;
  background-image: url("../images/pattern.jpeg");
}

<img src="./resources/images/hacksaw.jpeg" alt="Hacksaw" />
