### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by ghost** [SmeetaPatel/prj-rev-bwfs-dasmoto#5]
https://github.com/SmeetaPatel/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L16

Your pricing information should be _inline_ within the product information paragraph. Instead of using a `p` tag, you should use a `span` which is inline.

Rather than give each pricing element it's own ID, you should give them all the same class so that you can easily select the all as a group using a single selector. Use a descriptive class name like `price` or `cost`.

**Comment by SmeetaPatel** [comment]
<div class="product">
   <h2 id="frame">Frames</h2>
   <img src="./resources/images/frames.jpeg" alt="Frames" />
   <h3>Art Frames (Assorted)</h3>
   <p>Assorted frames made from different material, including MDF, birchwood,
   and PDE. Select frames can be sanded and painted according to your needs. </p>
   <span class="price">Starting at $2.00/frame</span>
  </div>

.price {
display:inline;
color: blue;
}
