### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [SmeetaPatel/prj-rev-bwfs-dasmoto#7]
Satisfactory 👍 

You've successfully reproduced the website according to the design mock.

See if you can come to this and refactor your HTML to make more strategic use of `div` tags, classes, and IDs. Then try to use these to refactor your CSS and keep it as concise and understandable as possible.

**Comment by SmeetaPatel** [comment]
Hi Steve,

Thanks so much for your constructive feedback. I'll  tried refactoring the code but for some reason it didn't work and I couldn't detect the issue. I'm definitely going to re-write the code taking your comments on board.

**Comment by SmeetaPatel** [comment]
Thanks fixed all the items as per your comments. Very helpful. Thanks
